package monocle.std

trait StdInstances
  extends BooleanOptics
  with    ByteOptics
  with    CharOptics
  with    DoubleOptics
  with    EitherOptics
  with    FunctionOptics
  with    IntOptics
  with    ListOptics
  with    LongOptics
  with    MapOptics
  with    OptionOptics
  with    SetOptics
  with    StreamOptics
  with    StringOptics
  with    Tuple2Optics
  with    Tuple3Optics
  with    Tuple4Optics
  with    Tuple5Optics
  with    Tuple6Optics
  with    VectorOptics
